# Generated by Django 4.2.2 on 2024-01-12 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('area', models.CharField(max_length=255, verbose_name='область обследования')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ct_images/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('contrast_enhancement', models.BooleanField(default=False, verbose_name='контрастное усиление')),
            ],
            options={
                'verbose_name': 'КТ-исследование',
                'verbose_name_plural': 'КТ-исследования',
            },
        ),
        migrations.CreateModel(
            name='MRIStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('area', models.CharField(max_length=255, verbose_name='область обследования')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mri_images/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('contrast_enhancement', models.BooleanField(default=False, verbose_name='контрастное усиление')),
            ],
            options={
                'verbose_name': 'МРТ-исследование',
                'verbose_name_plural': 'МРТ-исследования',
            },
        ),
        migrations.CreateModel(
            name='PETCTStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('area', models.CharField(max_length=255, verbose_name='область обследования')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ct_images/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('contrast_enhancement', models.BooleanField(default=False, verbose_name='контрастное усиление')),
                ('pet_tracer', models.CharField(choices=[('18F-FDG', '18F-фтордезоксиглюкоза'), ('11C-methionine', '11C-метионин')], max_length=55, verbose_name='радиофармпрепарат')),
            ],
            options={
                'verbose_name': 'ПЭТ/КТ-исследование',
                'verbose_name_plural': 'ПЭТ/КТ-исследования',
            },
        ),
        migrations.CreateModel(
            name='USStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('area', models.CharField(max_length=255, verbose_name='область обследования')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='us_images/', verbose_name='изображение')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('doppler', models.BooleanField(default=False, verbose_name='допплерография')),
            ],
            options={
                'verbose_name': 'УЗ-исследеование',
                'verbose_name_plural': 'УЗ-исследования',
            },
        ),
        migrations.CreateModel(
            name='USOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.DurationField(verbose_name='продолжительность')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsite.usstudy', verbose_name='исследование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись на исследование',
                'verbose_name_plural': 'записи на исследования',
            },
        ),
        migrations.CreateModel(
            name='PETCTOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.DurationField(verbose_name='продолжительность')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsite.petctstudy', verbose_name='исследование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись на исследование',
                'verbose_name_plural': 'записи на исследования',
            },
        ),
        migrations.CreateModel(
            name='MRIOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.DurationField(verbose_name='продолжительность')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsite.mristudy', verbose_name='исследование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись на исследование',
                'verbose_name_plural': 'записи на исследования',
            },
        ),
        migrations.CreateModel(
            name='CTOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.DurationField(verbose_name='продолжительность')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsite.ctstudy', verbose_name='исследование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись на исследование',
                'verbose_name_plural': 'записи на исследования',
            },
        ),
    ]
