# Generated by Django 4.2.2 on 2024-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0002_alter_petctorder_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctorder',
            name='duration',
            field=models.DurationField(default=60.0, verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='mriorder',
            name='duration',
            field=models.DurationField(default=60.0, verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='usorder',
            name='duration',
            field=models.DurationField(default=30.0, verbose_name='продолжительность'),
        ),
    ]
