# Generated by Django 4.2.2 on 2024-01-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsite', '0003_alter_ctorder_duration_alter_mriorder_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('email', models.CharField(max_length=150, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=10, verbose_name='телефон')),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
